# -*- coding: utf-8 -*-
"""FAU Geoscience AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11otuilTjUUTHQ8ELvKE0AcuAkh4WS1oY

# 🌍 Climate Data Lesson: Miami Temperatures (2000–2020)

In this lesson, we will:
- Learn how to fetch real NOAA climate data (daily summaries)
- Clean and explore the dataset
- Compute annual averages (calculating `TAVG` when missing)
- Visualize climate data with line charts
- Animate year-by-year to see long-term warming trends
- Add a regression line to highlight the climate signal

## Step 1: Import Libraries
We’ll use **requests** (to fetch data), **pandas** (for tables), and **matplotlib** (for plots).
"""

import requests
import pandas as pd
import matplotlib.pyplot as plt
import time
from IPython.display import clear_output, display

"""## Step 2: Fetch Data from NOAA
We’ll use the **NOAA Access Data Service API**.

We will fetch **TMAX, TMIN, and TAVG** for Miami International Airport from 2000–2020.
"""

url = "https://www.ncei.noaa.gov/access/services/data/v1"

params = {
    "dataset": "daily-summaries",
    "stations": "USW00012839",   # Miami International Airport
    "startDate": "2000-01-01",
    "endDate": "2024-12-31",
    "dataTypes": "TMAX,TMIN,TAVG",
    "units": "metric",
    "format": "json"
}

print("Fetching data from NOAA...")
r = requests.get(url, params=params, timeout=60)
print("Status:", r.status_code)
data = r.json()
print("Records fetched:", len(data))

"""## Step 3: Load Data into Pandas
Convert the JSON into a **DataFrame** and preview the first few rows.
"""

df = pd.DataFrame(data)
df.head()

"""## Step 4: Clean Data
- Convert the `DATE` column to datetime
- Convert `TAVG`, `TMAX`, `TMIN` to numeric
- Fill missing `TAVG` using `(TMAX+TMIN)/2`
- Add a `year` column for grouping
"""

df["DATE"] = pd.to_datetime(df["DATE"])

# Convert to numeric
for col in ["TAVG", "TMAX", "TMIN"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Fill missing TAVG with (TMAX + TMIN) / 2
df["TAVG"] = df["TAVG"].fillna((df["TMAX"] + df["TMIN"]) / 2)

# Add year column
df["year"] = df["DATE"].dt.year
df.head()

"""## Step 5: Explore a Single Year (Daily Temps)
Let’s look at **Miami in 2000** — daily average temperatures.
"""

df_2000 = df[df["year"] == 2000]
plt.figure(figsize=(10,5))
plt.plot(df_2000["DATE"], df_2000["TAVG"])
plt.title("Miami Daily Avg Temperature (2000)")
plt.xlabel("Date")
plt.ylabel("Temperature (°C)")
plt.grid(True)
plt.show()

"""## Step 6: Compute Annual Averages
Group the data by year and compute the mean `TAVG`.
"""

annual_avg = df.groupby("year")["TAVG"].mean()
annual_avg

"""## Step 7: Plot Annual Averages
Now let’s plot all years at once.
"""

plt.figure(figsize=(10,5))
plt.plot(annual_avg.index, annual_avg.values, marker="o", color="blue")
plt.title("Miami Annual Avg Temperature (2000–2020)")
plt.xlabel("Year")
plt.ylabel("Temperature (°C)")
plt.grid(True)
plt.show()

"""## Step 8: Animate Year-by-Year
Watch the climate trend build **year by year**.
"""

for year in annual_avg.index:
    clear_output(wait=True)
    print(f"Processing year {year}...")

    fig, ax = plt.subplots(figsize=(10,5))
    ax.plot(annual_avg.loc[:year].index, annual_avg.loc[:year].values,
            marker="o", color="blue")
    ax.set_title("Miami Annual Avg Temperature (2000–2020)")
    ax.set_xlabel("Year")
    ax.set_ylabel("Temperature (°C)")
    ax.grid(True)
    display(fig)
    plt.close(fig)
    time.sleep(0.8)

"""## Step 9: Add a Regression Line
Finally, let’s fit a linear trend line to highlight warming.
"""

import numpy as np

x = annual_avg.index.values
y = annual_avg.values
coeffs = np.polyfit(x, y, 1)  # slope, intercept
trend = np.poly1d(coeffs)

plt.figure(figsize=(10,5))
plt.plot(x, y, marker="o", color="blue", label="Annual Avg")
plt.plot(x, trend(x), color="red", linestyle="--", label="Trend line")
plt.title("Miami Annual Avg Temperature with Trend (2000–2020)")
plt.xlabel("Year")
plt.ylabel("Temperature (°C)")
plt.legend()
plt.grid(True)
plt.show()

print(f"Trend slope: {coeffs[0]:.3f} °C/year")



df["month"] = df["DATE"].dt.month
monthly_clim = df.groupby("month")["TAVG"].mean()

plt.figure(figsize=(8,5))
plt.plot(monthly_clim.index, monthly_clim.values, marker="o", color="green")
plt.xticks(range(1,13), ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"])
plt.title("Miami Monthly Climatology (2000–2020)")
plt.xlabel("Month")
plt.ylabel("Temperature (°C)")
plt.grid(True)
plt.show()

import seaborn as sns

df["dayofyear"] = df["DATE"].dt.dayofyear
pivot = df.pivot_table(index="year", columns="dayofyear", values="TAVG")

plt.figure(figsize=(15,6))
sns.heatmap(pivot, cmap="coolwarm", cbar_kws={'label': '°C'})
plt.title("Miami Daily Avg Temperature Heatmap (2000–2020)")
plt.xlabel("Day of Year")
plt.ylabel("Year")
plt.show()



import folium

# Miami station coords
miami_coords = [25.793, -80.290]  # approx location of station

m = folium.Map(location=miami_coords, zoom_start=7)
folium.Marker(
    location=miami_coords,
    popup="Miami Intl Airport (USW00012839)",
    tooltip="Click for info",
    icon=folium.Icon(color="red", icon="info-sign")
).add_to(m)

m

# Fetch New York station with TMAX, TMIN, TAVG
params_ny = {
    "dataset": "daily-summaries",
    "stations": "USW00094728",  # New York Central Park
    "startDate": "2000-01-01",
    "endDate": "2024-12-31",
    "dataTypes": "TMAX,TMIN,TAVG",
    "units": "metric",
    "format": "json"
}

r2 = requests.get(url, params=params_ny, timeout=60)
df_ny = pd.DataFrame(r2.json())

# Clean
df_ny["DATE"] = pd.to_datetime(df_ny["DATE"])
for col in ["TAVG", "TMAX", "TMIN"]:
    df_ny[col] = pd.to_numeric(df_ny[col], errors="coerce")

# Fill missing TAVG
df_ny["TAVG"] = df_ny["TAVG"].fillna((df_ny["TMAX"] + df_ny["TMIN"]) / 2)
df_ny["year"] = df_ny["DATE"].dt.year

# Annual averages
annual_ny = df_ny.groupby("year")["TAVG"].mean()

# Plot comparison again
plt.figure(figsize=(10,5))
plt.plot(annual_avg.index, annual_avg.values, marker="o", label="Miami")
plt.plot(annual_ny.index, annual_ny.values, marker="s", label="New York")
plt.title("Annual Avg Temperature: Miami vs New York (2000–2020)")
plt.xlabel("Year")
plt.ylabel("Temperature (°C)")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10,5))
plt.plot(annual_avg.index, annual_avg.values, marker="o", alpha=0.5, label="Annual Avg")
plt.plot(annual_avg.index, annual_avg.rolling(5).mean(), color="red", linewidth=2, label="5-Year Rolling Mean")
plt.title("Miami Annual Avg Temperature with 5-Year Smoothing")
plt.xlabel("Year")
plt.ylabel("Temperature (°C)")
plt.legend()
plt.grid(True)
plt.show()

















!pip install cartopy
import cartopy

import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

# Example stations with coords and mean temps
stations = {
    "Miami Intl Airport": {"coords": (25.793, -80.290), "mean": annual_avg.mean()},
    "New York Central Park": {"coords": (40.782, -73.965), "mean": annual_ny.mean()}
}

# Create map
fig = plt.figure(figsize=(10,8))
ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_extent([-100, -65, 20, 50])  # US East

# Add map features
ax.add_feature(cfeature.LAND, facecolor="lightgray")
ax.add_feature(cfeature.OCEAN, facecolor="lightblue")
ax.add_feature(cfeature.BORDERS, linestyle=":")
ax.add_feature(cfeature.STATES, linestyle=":")

# Plot stations
for name, info in stations.items():
    lat, lon = info["coords"]
    mean_temp = info["mean"]
    ax.plot(lon, lat, marker="o", markersize=10, color="red", transform=ccrs.PlateCarree())
    ax.text(lon+0.5, lat+0.5, f"{name}\n{mean_temp:.1f} °C",
            transform=ccrs.PlateCarree(), fontsize=9)

plt.title("Station Annual Avg Temperatures (2000–2020)")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

# Example grid (lat/lon + fake temperature field)
lats = np.linspace(20, 50, 60)
lons = np.linspace(-100, -65, 70)
lon2d, lat2d = np.meshgrid(lons, lats)

# Fake "temperature field" centered on SE US
temp = 25 - 0.1*(lat2d-30)**2 - 0.05*(lon2d+80)**2 + np.random.normal(0,0.5,lon2d.shape)

# --- Create rich map ---
fig = plt.figure(figsize=(12,8))
ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_extent([-100, -65, 20, 50])

# Features
ax.add_feature(cfeature.COASTLINE)
ax.add_feature(cfeature.STATES, linestyle=":")
ax.add_feature(cfeature.BORDERS)

# Filled contours
c = ax.contourf(lon2d, lat2d, temp,
                transform=ccrs.PlateCarree(),
                cmap="coolwarm", levels=np.linspace(temp.min(), temp.max(), 20))

# Contour lines
ax.contour(lon2d, lat2d, temp, colors="black", linewidths=0.5, transform=ccrs.PlateCarree())

# Colorbar
plt.colorbar(c, orientation="vertical", label="Temperature (°C)", shrink=0.7)

plt.title("Example Rich Weather Map: Temperatures over Eastern US")
plt.show()

# --- Install cartopy if needed (Colab only) ---
# !apt-get install -y libproj-dev proj-data proj-bin libgeos-dev
# !pip install cartopy xarray netCDF4

import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

# --- 1. Load dataset ---
url = "https://downloads.psl.noaa.gov/Datasets/ncep.reanalysis.derived/surface/air.mon.mean.nc"
ds = xr.open_dataset(url)

print(ds)

# --- 2. Extract Eastern US region for July 2010 ---
# lat is descending (90 → -90), so slice(50,20)
# lon is 0–360, so -100 → 260 and -65 → 295
temp = ds["air"].sel(
    time="2010-07-01",
    lat=slice(50, 20),
    lon=slice(260, 295)
)

print("Subset shape:", temp.shape)
print("Temp range:", float(temp.min()), "to", float(temp.max()))

# --- 3. Plot map ---
fig = plt.figure(figsize=(10,8))
ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_extent([-100, -65, 20, 50])  # Eastern US in -180–180 system

# Add map features
ax.add_feature(cfeature.COASTLINE)
ax.add_feature(cfeature.BORDERS)
ax.add_feature(cfeature.STATES, linestyle=":")

# Filled contour
c = ax.contourf(
    temp["lon"], temp["lat"], temp,
    transform=ccrs.PlateCarree(),
    cmap="coolwarm", levels=20
)

# Colorbar
plt.colorbar(c, orientation="vertical", label="Surface Air Temp (°C)", shrink=0.7)

plt.title("NCEP/NCAR Reanalysis: Surface Air Temperature (July 2010)")
plt.show()

import matplotlib.pyplot as plt
import matplotlib.animation as animation

# Extract 2010 data for Eastern US
subset = ds["air"].sel(
    time=slice("2010-01-01", "2010-12-01"),
    lat=slice(50, 20),
    lon=slice(260, 295)
)

# Set up figure
fig, ax = plt.subplots(figsize=(10,8), subplot_kw={'projection': ccrs.PlateCarree()})
ax.set_extent([-100, -65, 20, 50])
ax.add_feature(cfeature.COASTLINE)
ax.add_feature(cfeature.STATES, linestyle=":")
ax.add_feature(cfeature.BORDERS)

# Initial frame
c = ax.contourf(
    subset["lon"], subset["lat"], subset.isel(time=0),
    transform=ccrs.PlateCarree(), cmap="coolwarm", levels=20
)
title = ax.set_title(str(subset["time"].values[0])[:10])

# Colorbar
cb = fig.colorbar(c, orientation="vertical", shrink=0.7, label="Surface Air Temp (°C)")

# Update function for animation
def update(frame):
    ax.clear()
    ax.set_extent([-100, -65, 20, 50])
    ax.add_feature(cfeature.COASTLINE)
    ax.add_feature(cfeature.STATES, linestyle=":")
    ax.add_feature(cfeature.BORDERS)
    c = ax.contourf(
        subset["lon"], subset["lat"], subset.isel(time=frame),
        transform=ccrs.PlateCarree(), cmap="coolwarm", levels=20
    )
    ax.set_title(f"NCEP/NCAR Reanalysis: Surface Air Temp ({str(subset['time'].values[frame])[:10]})")
    return c

# Animate
ani = animation.FuncAnimation(fig, update, frames=len(subset["time"]), interval=1000, repeat=True)

# For Jupyter/Colab
from IPython.display import HTML
HTML(ani.to_jshtml())







from IPython.display import Image, display

gif_url = "https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/se/GEOCOLOR/20252691206-20252691601-GOES19-ABI-SE-GEOCOLOR-600x600.gif"
display(Image(url=gif_url))

from IPython.display import Image, display

def goes_latest(sector="se", product="GEOCOLOR", satellite="GOES19"):
    """
    Show latest available GOES loop for a region (sector) and product.
    """
    url = f"https://cdn.star.nesdis.noaa.gov/{satellite}/ABI/SECTOR/{sector}/{product}/{satellite}-{sector.upper()}-{product}-600x600.gif"
    print("Fetching:", url)
    display(Image(url=url))

# Example: Latest GEOCOLOR loop for SE US
goes_latest("se", "GEOCOLOR", "GOES19")



from IPython.display import Image, display

urls = [
    "https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/eus/GEOCOLOR/20252691216-20252691611-GOES19-ABI-EUS-GEOCOLOR-1000x1000.gif",
    "https://cdn.star.nesdis.noaa.gov/GOES19/GLM/SECTOR/eus/EXTENT3/20252691206-20252691606-GOES19-GLM-EUS-EXTENT3-1000x1000.gif",
    "https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/eus/AirMass/20252691221-20252691616-GOES19-ABI-EUS-AirMass-1000x1000.gif",
    "https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/eus/Sandwich/20252691216-20252691611-GOES19-ABI-EUS-Sandwich-1000x1000.gif",
    "https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/eus/DayNightCloudMicroCombo/20252691221-20252691616-GOES19-ABI-EUS-DayNightCloudMicroCombo-1000x1000.gif",
    "https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/eus/FireTemperature/20252691206-20252691601-GOES19-ABI-EUS-FireTemperature-1000x1000.gif",
    "https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/eus/14/20252691211-20252691606-GOES19-ABI-EUS-14-1000x1000.gif"
]

for url in urls:
    print("Fetching:", url)
    display(Image(url=url))

